-- create database (w/ PUBLIC schema)
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE security;

-- create users
USE ROLE USERADMIN;
CREATE OR REPLACE USER MARK;
CREATE OR REPLACE USER CLAUDE;
CREATE OR REPLACE USER MARY;

-- create roles
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE ADMIN;
CREATE OR REPLACE ROLE EDITOR;
CREATE OR REPLACE ROLE GUEST;
CREATE OR REPLACE ROLE RO_ROLE;
CREATE OR REPLACE ROLE RW_ROLE;
 
-- create the role hierarchy
GRANT ROLE ADMIN TO ROLE SYSADMIN;
GRANT ROLE EDITOR TO ROLE SYSADMIN;
GRANT ROLE GUEST TO ROLE SYSADMIN;
GRANT ROLE RO_ROLE TO ROLE ADMIN;
GRANT ROLE RW_ROLE TO ROLE ADMIN;
GRANT ROLE RO_ROLE TO ROLE EDITOR;
GRANT ROLE RW_ROLE TO ROLE EDITOR;
GRANT ROLE RO_ROLE TO ROLE GUEST;

-- assign roles to users
GRANT ROLE ADMIN TO USER MARK;
GRANT ROLE EDITOR TO USER CLAUDE;
GRANT ROLE GUEST TO USER MARY;

-- R/O privileges (RO_ROLE)
GRANT OPERATE, USAGE ON WAREHOUSE compute_wh TO ROLE RO_ROLE;

GRANT USAGE ON DATABASE security TO ROLE RO_ROLE;
GRANT USAGE ON SCHEMA security.public TO ROLE RO_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA security.public TO ROLE RO_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA security.public TO ROLE RO_ROLE;

-- R/W privileges (RW_ROLE)
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA security.public TO ROLE RW_ROLE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA security.public TO ROLE RW_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA security.public TO ROLE RW_ROLE;

-- ADMIN privileges (ADMIN)
GRANT ALL ON DATABASE security TO ROLE ADMIN;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE security TO ROLE ADMIN;